
POST http://localhost:8000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johna@ja.com"
}

###

POST http://localhost:8000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "5a36ec39-d307-49e0-ad25-11a10f8a1b06"
}

###

GET http://localhost:3003/balances/b150876f-b476-4573-bcea-1dfa5f74250a HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8000/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "2695dc3e-bcca-4ce3-9947-4c9e248d98f5",
    "account_id_to": "b150876f-b476-4573-bcea-1dfa5f74250a",
    "amount": 50
}